scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'web_server'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:3000']