version: "2.2"

volumes:
  postgres-data:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    user: "1000:1000"
    env_file:
      - .env
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "1000:1000"
    restart: always
    env_file:
      - .env
    ports:
      - 6969:3000
    volumes:
      - ./grafana:/var/lib/grafana
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
